server:
  port: 8080
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drivego_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: drivego_user
    password: your_password  # Replace with your actual password
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update  # This will create tables automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB
  web:
    resources:
      cache:
        period: 0
      static-locations: classpath:/static/
  h2:
    console:
      enabled: false
  thymeleaf:
    enabled: false
    cache: false
  flyway:
    enabled: false
  security:
    user:
      name: admin
      password: admin
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    com.drivego: DEBUG
    org.springframework.web: DEBUG